### ISSUE TITLE
[Bug]: Enchantment related settings are not respected and stolen icon is missing on some items

### ISSUE THREAD

**Issue by CaptainRay1993** [MissCorruption/QuickLootEE-NG#65] opened 2024-11-23 01:08 UTC
### What happened? (Actual vs Expected Behavior)

![20241123084649_1](https://github.com/user-attachments/assets/ce4ef8e5-34e7-4caa-a540-6177a4299af8)
![20241123084700_1](https://github.com/user-attachments/assets/622076cd-eb14-43fc-a92e-6acd27fd919a)
![20241123084717_1](https://github.com/user-attachments/assets/55b732dc-1891-46ac-b2ef-688c152ce849)
As you can see from above screenshots, the special and known enchantment icons still show even if I set them disabled and the backpack is marked stolen in skyui while not in quickloot(This bug occurs when opening the container itself is not marked as stolen but taking the items within is)

### What mods for icons where you using, if any?

None. Only with I4

### Steps to Reproduce

Just disabled the show special and known enchantment icons in the MCM and search the furniture in the Dragonsreach.

### Version

2.0.0

### What Skyrim version are you using?

1.6.1170

### Relevant log output (Expandable)

```shell
[2024-11-23 08:53:22.434] [info] [17860] [XSEPlugin.cpp:130] Loaded plugin QuickLootIE 2-0-0-0
[2024-11-23 08:53:22.434] [info] [17860] [RequestServer.h:126] Initializing request server with api version 1.0
[2024-11-23 08:53:22.434] [info] [17860] [RequestServer.h:160] Registered query handler for request type 256 (kRegisterTakingItemHandler), request data [8:struct QuickLoot::Events::HandlerRegistrationRequest<struct QuickLoot::Events::TakingItemEvent>], response data [1:bool]
[2024-11-23 08:53:22.434] [info] [17860] [RequestServer.h:160] Registered query handler for request type 257 (kRegisterTakeItemHandler), request data [8:struct QuickLoot::Events::HandlerRegistrationRequest<struct QuickLoot::Events::TakeItemEvent>], response data [1:bool]
[2024-11-23 08:53:22.434] [info] [17860] [RequestServer.h:160] Registered query handler for request type 258 (kRegisterSelectItemHandler), request data [8:struct QuickLoot::Events::HandlerRegistrationRequest<struct QuickLoot::Events::SelectItemEvent>], response data [1:bool]
[2024-11-23 08:53:22.434] [info] [17860] [RequestServer.h:160] Registered query handler for request type 259 (kRegisterOpeningLootMenuHandler), request data [8:struct QuickLoot::Events::HandlerRegistrationRequest<struct QuickLoot::Events::OpeningLootMenuEvent>], response data [1:bool]
[2024-11-23 08:53:22.434] [info] [17860] [RequestServer.h:160] Registered query handler for request type 260 (kRegisterOpenLootMenuHandler), request data [8:struct QuickLoot::Events::HandlerRegistrationRequest<struct QuickLoot::Events::OpenLootMenuEvent>], response data [1:bool]
[2024-11-23 08:53:22.434] [info] [17860] [RequestServer.h:160] Registered query handler for request type 261 (kRegisterCloseLootMenuHandler), request data [8:struct QuickLoot::Events::HandlerRegistrationRequest<struct QuickLoot::Events::CloseLootMenuEvent>], response data [1:bool]
[2024-11-23 08:53:22.434] [info] [17860] [RequestServer.h:160] Registered query handler for request type 262 (kRegisterInvalidateLootMenuHandler), request data [8:struct QuickLoot::Events::HandlerRegistrationRequest<struct QuickLoot::Events::InvalidateLootMenuEvent>], response data [1:bool]
[2024-11-23 08:53:22.434] [info] [17860] [HUDManager.h:38] Installed class HUDManager::Handler<195816>
[2024-11-23 08:53:22.434] [info] [17860] [HUDManager.h:38] Installed class HUDManager::Handler<189485>
[2024-11-23 08:53:22.434] [info] [17860] [HUDManager.h:38] Installed class HUDManager::Handler<189633>
[2024-11-23 08:53:22.434] [info] [17860] [HUDManager.h:23] Installed class HUDManager
[2024-11-23 08:53:22.435] [info] [17860] [Hooks.cpp:12] Installed all hooks
[2024-11-23 08:53:41.482] [info] [18952] [Animation.h:93] Installed class Animation::AnimationManager
[2024-11-23 08:53:41.482] [info] [18952] [Events.h:27] Registered struct SKSE::CrosshairRefEvent
[2024-11-23 08:53:41.482] [info] [18952] [Events.h:33] Registered struct RE::TESLockChangedEvent
[2024-11-23 08:53:41.482] [info] [18952] [Events.cpp:137] Registered class Events::LifeStateManager
[2024-11-23 08:53:41.482] [info] [18952] [Events.h:214] Registered class Events::LockedContainerManager
[2024-11-23 08:53:41.482] [info] [18952] [Events.h:153] Registered class Events::CombatManager
[2024-11-23 08:53:41.482] [info] [18952] [Events.h:270] Registered all event handlers
[2024-11-23 08:53:41.482] [info] [18952] [LootMenu.h:36] Registered LootMenu
[2024-11-23 08:53:41.482] [info] [18952] [LOTD.h:37] Plugin DBM_RelicNotifications.esp not found
[2024-11-23 08:53:41.482] [warning] [18952] [Interfaces.cpp:272] Failed to dispatch message to Completionist
[2024-11-23 08:53:41.482] [error] [18952] [RequestClient.h:26] Failed to connect to plugin Completionist (failed to deliver)
[2024-11-23 08:53:46.301] [info] [19304] [Papyrus.cpp:65] MCM pointer set successfully
[2024-11-23 08:53:46.301] [info] [19304] [Papyrus.h:145] QLIEWindowScale: 1
[2024-11-23 08:53:46.302] [info] [19304] [Papyrus.h:145] QLIETransparency_Normal: 1
[2024-11-23 08:53:46.302] [info] [19304] [Papyrus.h:145] QLIETransparency_Empty: 0.3
[2024-11-23 08:53:46.302] [info] [19304] [Papyrus.h:151] user_selected_sort_options: 0 strings
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AtomCrafty** [comment] 2024-11-24 00:19
![image](https://github.com/user-attachments/assets/36a22581-1072-4b1a-8ffe-68464e7f59e0)
I can't reproduce either of these in the latest dev build, so I assume both were fixed by the recent rewrites.

**Comment by CaptainRay1993** [comment] 2024-11-24 05:39
Great. Would you like to share the latest dev build so I can test it further or any ETA of next release?

**Closed as completed** 2024-11-25 21:52 UTC
Labels: bug
